global:
  resolve_timeout: 5m

route:
  receiver: log-receiver
  group_by: ['alertname', 'job', 'env']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h

receivers:
  - name: log-receiver
    webhook_configs:
      - url: http://127.0.0.1:5001/
        send_resolved: true
