apiVersion: 1

contactPoints:
  - orgId: 1
    name: Alertmanager
    receivers:
      - uid: alertmanager
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager:9093
          disableResolveMessage: false
