apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agnos-devops-prod

resources:
  - namespace.yaml
  - ../../base
  - secret.yaml
  
images:
  - name: ghcr.io/sornsub/agnos-api
    newTag: prod-latest
  - name: ghcr.io/sornsub/agnos-worker
    newTag: prod-latest

patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: HorizontalPodAutoscaler
      name: api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
