apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: agnos-devops
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - port: 8001
      targetPort: 8001
      name: metrics
  type: ClusterIP
