apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: agnos-devops
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.4
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-json
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-provider
          configMap:
            name: grafana-dashboards-provider
        - name: grafana-dashboard-json
          configMap:
            name: grafana-dashboard-agnos-overview
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: agnos-devops
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: agnos-dashboards
        orgId: 1
        folder: Agnos
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: agnos-devops
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: ClusterIP # Change to LoadBalancer for demo access
  # type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
