apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agnos-devops-uat

resources:
  - namespace.yaml
  - ../../base
  - secret.yaml

images:
  - name: ghcr.io/sornsub/agnos-api
    newTag: uat-latest
  - name: ghcr.io/sornsub/agnos-worker
    newTag: uat-latest

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: app-config
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
      name: api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5
